# With this setup you can Test the Storybook setup integrated with TYPO3, Fluid, EXT:storybook, Storybook and the Storybook Framework package
services:
  typo3:
    image: ghcr.io/pluswerk/php-dev:nginx-${PHP_IMAGE_VERSION:-8.4}-alpine
    working_dir: ${DOCKER_ROOT_PWD}/Documentation/dummy-project
    volumes:
      - ${DOCKER_ROOT_PWD}:${DOCKER_ROOT_PWD}
    environment:
      WEB_DOCUMENT_ROOT: ${DOCKER_ROOT_PWD}/Documentation/dummy-project/public
      TYPO3_CONTEXT: Development
      APPLICATION_UID: ${APPLICATION_UID:-1000}
    ports:
      - "8011:80"
    healthcheck:
      test: curl --fail-with-body -X OPTIONS http://localhost:80/_storybook/preview

  playwright:
    image: mcr.microsoft.com/playwright:v1.54.1-noble
    working_dir: ${DOCKER_ROOT_PWD}/Documentation/dummy-project
    volumes:
      - ${DOCKER_ROOT_PWD}:${DOCKER_ROOT_PWD}
      - ${X11_SOCKET:-./nope}:/tmp/.X11-unix
    user: '0'
    environment:
      STORYBOOK_TYPO3_ENDPOINT: http://typo3:80/
      DISPLAY: ${DISPLAY:-}
      CI: 1
      FORCE_COLOR: 1
    ports:
      - "6060:8080"
    depends_on:
      typo3:
        condition: service_healthy
